-- V33 : composition corporelle Visbody (rapports PDF reçus par email).

-- Prénom / nom de l'utilisateur — sert à identifier le destinataire d'un rapport
-- (champ « ID » du PDF) et à l'affichage.
ALTER TABLE utilisateur ADD COLUMN prenom VARCHAR(100);
ALTER TABLE utilisateur ADD COLUMN nom    VARCHAR(100);

-- Un enregistrement par scan Visbody. mesure_le = « Temps de détection » du rapport.
CREATE TABLE body_composition_record (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id           BIGINT NOT NULL REFERENCES utilisateur(id) ON DELETE CASCADE,
    mesure_le                TIMESTAMP NOT NULL,
    note                     INTEGER,

    -- Composition globale (kg sauf indication).
    poids                    DOUBLE PRECISION,
    masse_musculaire         DOUBLE PRECISION,   -- Masse musculaire
    mms                      DOUBLE PRECISION,   -- Masse musculaire squelettique
    mgc                      DOUBLE PRECISION,   -- Masse grasse corporelle
    mmc                      DOUBLE PRECISION,   -- Masse maigre (fat-free)
    tgc_pct                  DOUBLE PRECISION,   -- Taux de graisse corporelle (%)
    imc                      DOUBLE PRECISION,   -- kg/m²
    rth                      DOUBLE PRECISION,   -- Ratio taille/hanche
    mb_kcal                  DOUBLE PRECISION,   -- Métabolisme de base (kcal/j)
    age_metabolique          DOUBLE PRECISION,
    graisse_viscerale        DOUBLE PRECISION,
    eau_totale               DOUBLE PRECISION,
    eau_intra                DOUBLE PRECISION,
    eau_extra                DOUBLE PRECISION,
    ratio_ecw_tbw            DOUBLE PRECISION,
    masse_proteine           DOUBLE PRECISION,
    sel_inorganique          DOUBLE PRECISION,

    -- Masse grasse par segment (kg).
    mgc_bras_gauche          DOUBLE PRECISION,
    mgc_bras_droit           DOUBLE PRECISION,
    mgc_tronc                DOUBLE PRECISION,
    mgc_jambe_gauche         DOUBLE PRECISION,
    mgc_jambe_droite         DOUBLE PRECISION,

    -- Masse musculaire par segment (kg).
    muscle_bras_gauche       DOUBLE PRECISION,
    muscle_bras_droit        DOUBLE PRECISION,
    muscle_tronc             DOUBLE PRECISION,
    muscle_jambe_gauche      DOUBLE PRECISION,
    muscle_jambe_droite      DOUBLE PRECISION,

    source                   VARCHAR(32) NOT NULL DEFAULT 'VISBODY_PDF',
    created_at               TIMESTAMP NOT NULL DEFAULT now(),

    -- Idempotence : un même scan (même instant) n'est importé qu'une fois.
    CONSTRAINT uq_body_composition_user_mesure UNIQUE (utilisateur_id, mesure_le)
);

CREATE INDEX idx_body_composition_user_date
    ON body_composition_record (utilisateur_id, mesure_le);
