package com.kronos.chiron.exercice.model;

public enum MuscleGroup {
    PECTORAUX, DOS, EPAULES, BICEPS, TRICEPS, ABDOMINAUX, QUADRICEPS, ISCHIO_JAMBIERS, FESSIERS, MOLLETS, AVANT_BRAS, TRAPEZES, LOMBAIRES, ADDUCTEURS, ABDUCTEURS, CARDIO
}
